-- CreateTable
CREATE TABLE "USER" (
    "id" SERIAL NOT NULL,
    "xp" INTEGER NOT NULL DEFAULT 0,
    "level" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "USER_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ACHIEVEMENT" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "xp_reward" INTEGER NOT NULL,
    "icon" TEXT NOT NULL DEFAULT 'mdi-trophy',

    CONSTRAINT "ACHIEVEMENT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "USER_ACHIEVEMENT" (
    "id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "achievement_id" INTEGER NOT NULL,
    "earned_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "USER_ACHIEVEMENT_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DAILY_QUEST" (
    "id" SERIAL NOT NULL,
    "name" VARCHAR(100) NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "xp_reward" INTEGER NOT NULL,
    "type" VARCHAR(50) NOT NULL,
    "target" INTEGER NOT NULL DEFAULT 1,

    CONSTRAINT "DAILY_QUEST_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "USER_QUEST" (
    "id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "quest_id" INTEGER NOT NULL,
    "current_value" INTEGER NOT NULL DEFAULT 0,
    "is_completed" BOOLEAN NOT NULL DEFAULT false,
    "last_updated" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "USER_QUEST_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "USER_ACHIEVEMENT" ADD CONSTRAINT "USER_ACHIEVEMENT_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_ACHIEVEMENT" ADD CONSTRAINT "USER_ACHIEVEMENT_achievement_id_fkey" FOREIGN KEY ("achievement_id") REFERENCES "ACHIEVEMENT"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_QUEST" ADD CONSTRAINT "USER_QUEST_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "USER"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "USER_QUEST" ADD CONSTRAINT "USER_QUEST_quest_id_fkey" FOREIGN KEY ("quest_id") REFERENCES "DAILY_QUEST"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
